const chai = require('chai')

const { isCpf } = require('./../')

const expect = chai.expect

describe('testing isCpf', () => {
  it('an invalid cpf', () => {
    expect(isCpf('341.302.151-86')).to.be.false
    expect(isCpf('341.302.151-861')).to.be.false
    expect(isCpf('111.111.111-11')).to.be.false
    expect(isCpf('222.222.222-22')).to.be.false
    expect(isCpf('333.333.333-33')).to.be.false
    expect(isCpf('444.444.444-44')).to.be.false
    expect(isCpf('555.555.555-55')).to.be.false
    expect(isCpf('666.666.666-66')).to.be.false
    expect(isCpf('777.777.777-77')).to.be.false
    expect(isCpf('888.888.888-88')).to.be.false
    expect(isCpf('999.999.999-99')).to.be.false
    expect(isCpf('000.000.000-00')).to.be.false
  })

  it('a valid cpf', () => {
    // CPF generated by https://www.4devs.com.br/gerador_de_cpf
    expect(isCpf('341.302.150-86')).to.be.true
  })
})
